apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudvideouploader
  namespace: cloudvideouploader
  labels:
    app: cloudvideouploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudvideouploader
  template:
    metadata:
      labels:
        app: cloudvideouploader
    spec:
      containers:
        - name: api
          image: cloudvideouploader:0.1.5   # <-- bump tag when you rebuild
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: AzureStorage__BlobConnectionString
              value: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1"
            - name: AzureStorage__QueueConnectionString
              value: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1"
            - name: AzureStorage__BlobContainerName
              value: "videos"
            - name: AzureStorage__QueueName
              value: "video-processing"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cloudvideouploader
  namespace: cloudvideouploader
  labels:
    app: cloudvideouploader
spec:
  selector:
    app: cloudvideouploader
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
