name: build-and-push-acr
on:
  workflow_dispatch: {}
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # optional sanity
      - run: ls -la

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .            # repo root (matches your screenshot)
          file: ./Dockerfile    # repo root Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/cloudvideouploader:dotnet2
